article/urls.py
from django.urls import path

from . import views
from .views import ArticlesByCategoryView, DetailArticleView

app_name = 'articles'
urlpatterns = [
    path('politique/', ArticlesByCategoryView.as_view(), {'category_name': 'politique'}, name='politiques'),
    path('economie/', ArticlesByCategoryView.as_view(), {'category_name': 'eco'}, name='eco'),
    path('finances/', ArticlesByCategoryView.as_view(), {'category_name': 'finances'}, name='articlefinance'),
    path('societe/', ArticlesByCategoryView.as_view(), {'category_name': 'societe'}, name='articlesociete'),
    path('innovation/', ArticlesByCategoryView.as_view(), {'category_name': 'entreprise'}, name='entreprise'),
    path('international/', ArticlesByCategoryView.as_view(), {'category_name': 'international'}, name='internation'),
    path('<slug:slug>/', DetailArticleView.as_view(), name='detail_view')

]

infominutes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, re_path, include
from django.views.static import serve

from .views import home, rechercher

re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

urlpatterns = [

                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('rechercher', rechercher, name='rechercher'),
                  path('actualite/', include('article.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="congnd91">
    <title>INFO MINUTES | QUOTIDIEN D'INFORMATIONS</title>
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static '/images/favicon.png' %}">
    <link rel="apple-touch-icon" href="{% static '/images/apple-touch-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static '/images/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static '/images/apple-touch-icon-114x114.png' %}">
    <!-- Online Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Oswald:300,400,700&subset=latin-ext" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700" rel="stylesheet">
    <!-- Vender -->
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet" />
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static '/css/normalize.min.css' %}" rel="stylesheet" />
    <link href="{% static '/css/owl.carousel.min.css' %}" rel="stylesheet" />
    <!-- Main CSS (SCSS Compile) -->
    <link href="{% static '/css/main.css' %}" rel="stylesheet" />
    <!-- JavaScripts -->
    <!--<script src="js/modernizr.js"></script>-->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!--preload-->
    <div class="loader" id="page-loader">
        <div class="loading-wrapper">
        </div>
    </div>
    <!--menu mobile-->
    <nav class="menu-res hidden-lg hidden-md ">
        <div class="menu-res-inner">
            <ul>
                  <li><a href="{% url 'home' %}">ACCUEIL </a></li>

                     <li><a href="{% url 'articles:eco' %}">ECONOMIE</a></li>
                   <li><a href="{% url 'articles:articlefinance' %}">FINANCE </a></li>
                  <li><a href="{% url 'articles:politiques' %}">POLITIQUE</a></li>
                    <li><a href="{% url 'articles:articlesociete' %}">SOCIÉTÉ</a></li>
                    <li><a href="{% url 'articles:internation' %}">INTERNATIONAL</a></li>
                <li><a href="{% url 'articles:internation' %}">INNOVATION</a></li>
                <li><a href="{% url 'articles:internation' %}">PODCAST</a></li>



            </ul>
        </div>
    </nav>
    <div class="page">
        <div class="container">
            <!--header-->
            <header class="header">
                <div class="row">
                    <div class="col-md-3 col-sm-4 col-xs-12">
                        <a href="{% url 'home' %}" class="logo">
                            <img alt="Logo" src="/static/images/logo.png" />
                        </a>
                    </div>
                    <div class="col-md-6 col-md-offset-3 col-sm-8  text-right col-xs-12 hidden-xs">
                        <!--div class="owl-carousel owl-special">
                            <div>
                                <div class="special-news">
                                    <a href="#">
                                        <img alt="" src="/static/images/product/17.jpg" />
                                    </a>
                                    <h3><a href="#">Apple iPhone 7 review </a></h3>
                                    <div class="meta-post">
                                        <a href="#">
                                            Ashley Ford
                                        </a>
                                        <em></em>
                                        <span>
                                            21 Sep 2016
                                        </span>
                                    </div>
                                </div>
                            </div>

                        </div-->
                    </div>
                </div>
            </header>
            <!--menu-->

             <nav class="menu font-heading">
                <div class="menu-icon hidden-lg hidden-md">
                    <i class="fa fa-navicon"></i>
                    <span>MENU</span>
                </div>
                <ul class="hidden-sm hidden-xs">

                    <li><a href="{% url 'home' %}">ACCUEIL </a></li>

                     <li><a href="{% url 'articles:eco' %}">ECONOMIE</a></li>
                   <li><a href="{% url 'articles:articlefinance' %}">FINANCE </a></li>
                  <li><a href="{% url 'articles:politiques' %}">POLITIQUE</a></li>
                    <li><a href="{% url 'articles:articlesociete' %}">SOCIÉTÉ</a></li>
                    <li><a href="{% url 'articles:internation' %}">INTERNATIONAL</a></li>
                </ul>
                <div class="search-icon">
                    <div class="search-icon-inner">
                        <i class="fa fa-search"></i>
                    </div>
                    <div class="search-box">
                        <input type="text" placeholder="Search..." />
                        <button>Search</button>
                    </div>
                </div>
            </nav>


            {% block content %}{% endblock %}



        </div>
        <!--footer-->
        <footer class="footer">
            <div class="container">
                <!--All right-->
                <div class="allright">
                    <div class="row">
                        <div class="col-sm-6 col-xs-12">
                            <p> © 2023 <a href="#">INFO-MINUTES</a>. Tous droits réservés.</p>
                        </div>

                        <div class="col-sm-6 col-xs-12">
                            <ul class="list-social-icon list-social-icon-footer">
                                <li>
                                    <a href="#" class="facebook">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="twitter">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="google">
                                        <i class="fa fa-google"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="youtube">
                                        <i class="fa fa-youtube-play"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="pinterest">
                                        <i class="fa fa-pinterest-p"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="rss">
                                        <i class="fa fa-rss"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <!--scrip file-->
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.js' %}"></script>
    <script src="{% static '/js/owl.carousel.min.js' %}"></script>
    <script src="{% static '/js/main.js' %}"></script>
</body>
</html>